version: '3.1'
services:
  piping:
    image: nwtgck/piping-server:v0.15.4
    restart: always
    expose:
      - "80"
    command: --http-port=80

  caddy:
    build: ./caddy
    depends_on:
      - piping
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile:/Caddyfile
